### ISSUE TITLE
Upgrade time dependency

### ISSUE THREAD

**Issue by MHova** [SumAll/haskell-canteven-parsedate#14]
Just ran into some cabal hell because of `parsedate`'s hard dependency on `System.Locale`. `time-1.5.0.1` copied the `TimeLocale` stuff out of `System.Locale`.

Perhaps some compile time flags like this [example] (https://github.com/nh2/iso8601-time/commit/c218e5d7a75fd716e567c680dd74efee447e09cf) would help?

**Comment by glasserc** [comment]
Someone needs to really figure out what is going on with the ``time`` library.

**Comment by glasserc** [comment]
So, one unfortunate thing is that we use the ``rfc822DateFormat`` variable from old-locale. I'm not sure exactly what the nature of your problem was, but we'll still definitely depend on System.Locale unless we either want to break that format, or we want to copy the format string. (Maybe we should just do that.)

**Comment by glasserc** [comment]
Ah, turns out that gets re-exported in Time.Format. Let me see if I can manage this.

**Comment by taphu** [comment]
yeah. I believe that `canteven-parsedate` is not compatible with `time >= 1.5.0`. In other words, a major version bump in time broke `canteven-parsedate` because we weren't bounding the `time` versions.

**Comment by glasserc** [comment]
This got addressed by #17.
